### ISSUE TITLE
Postinstall script requires installation of karma-cli with global tag.

### ISSUE THREAD

**Issue by izy-izzy** [devrafalko/webpack-karma-jasmine#4]
Currently in a package.json is post-install script:
```
"postinstall": "npm install karma-cli -g"
```
I presume that the local package should not try to install some other package globally. This is currently cause me some issues when I try to have this package in my build as it fails the npm install. I do not have permission to install something globally for all the users nor it is the best option. Is it possible to remove a global ```-g``` modifier?

Thank you.

**Comment by devrafalko** [comment]
It's intended behaviour. `karma-cli` installed globally allows to use eg. `karma start` command directly from the command line rather than `./node_modules/karma/bin/karma start`. You would have to install `karma-cli` globally manually anyway. I considered it to be just a little bit more convenient solution.

**Comment by Waltari10** [comment]
I know this is closed, but there is no reason to have karma-cli installed globally. Global packages are something we are trying not to use at all, as it causes different developers to have different versions of the package, potentially causing issues when running the tests. 

I would very much be in favor of removing the postinstall script. I don't see how it is necessary.

**Comment by devrafalko** [comment]
Ok, I removed the post-install script in the new @3.0.8 version.

**Comment by izy-izzy** [comment]
Thank you
